### ISSUE TITLE
New information

### ISSUE THREAD

**Issue by algra4** [eschnou/covid19-be#28]
Sciensano added the new informations about the death (in hospital and retirement home).

I propose to add 2 columns (_daily_deceased_hospital_ & _daily_deceased_retirement_home_) and rename the column _daily_deceased_ to _daily_deceased_cumul_

**Comment by odony** [comment]
Do you see this the split between daily hospitals / retirement homes deaths in their data files on https://epistat.wiv-isp.be/covid/?
I don't see it, and their last "codebook" update was on April 6.

So far I've been visually extracting the data from their charts in the epidemiological bulletins (PDF). Which is quite tedious as you have to verify the whole dataset every day, because they correct deaths "at date" retrospectively as the data comes in.

**Comment by eschnou** [comment]
I would not rename existing columns to avoid breaking downstream applications, also the 'daily_deceased' is coherent with the rest of the naming.

No issues for me if you add daily_deceased_hospital & daily_deceased_retirement_home.

Thanks !
